name: Remote Task Creator
on:
  repository_dispatch:
    types: [create-task]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Issue
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"${{ github.event.client_payload.title }}","body":"${{ github.event.client_payload.body }} \n\n— Submitted via Web Dashboard"}'
